### ISSUE TITLE
Session's Close() method hangs

### ISSUE THREAD

**Issue by richardwilkes** [gocql/gocql#1031]
### What version of Cassandra are you using?
Cassandra 2.2.5

### What version of Gocql are you using?
commit 9ce8b08dfa5559eb86592129986654503cf40cf7

Calling gocql.Session's .Close() method causes a deadlock. I've narrowed it down to this minimal set of code to reproduce the issue:

```
package main

import (
	"fmt"

	"github.com/gocql/gocql"
)

func main() {
	cfg := gocql.NewCluster("<put your cassandra instance here>")
	cfg.SslOpts = &gocql.SslOptions{}
	sess, err := cfg.CreateSession()
	if err != nil {
		panic(err)
	}
	fmt.Println("About to close...")
	sess.Close()
	fmt.Println("Closed")  // <-- Never reaches this
}
```

The problem appears to be due to an error occurring in the Close() method when it is attempting to drain the connection pool. This causes it to call the HandleError method, which attempts to grab the lock again... but will be unable to since it already holds the lock.

```
goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0xc4203b0144, 0x900000000)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc4203b0140)
	/usr/local/Cellar/go/1.9.2/libexec/src/sync/mutex.go:134 +0x14c
sync.(*RWMutex).Lock(0xc4203b0140)
	/usr/local/Cellar/go/1.9.2/libexec/src/sync/rwmutex.go:93 +0x49
github.com/gocql/gocql.(*hostConnPool).HandleError(0xc4203b0100, 0xc420352700, 0x1bd4040, 0xc4204df2c0, 0x102dc01)
	/Users/rwilkes/code/go/src/github.com/gocql/gocql/connectionpool.go:534 +0x58
github.com/gocql/gocql.(*Conn).closeWithError(0xc420352700, 0x0, 0x0)
	/Users/rwilkes/code/go/src/github.com/gocql/gocql/conn.go:407 +0x33c
github.com/gocql/gocql.(*Conn).Close(0xc420352700)
	/Users/rwilkes/code/go/src/github.com/gocql/gocql/conn.go:416 +0x4b
github.com/gocql/gocql.(*hostConnPool).drainLocked(0xc4203b0100)
	/Users/rwilkes/code/go/src/github.com/gocql/gocql/connectionpool.go:562 +0xc8
github.com/gocql/gocql.(*hostConnPool).Close(0xc4203b0100)
	/Users/rwilkes/code/go/src/github.com/gocql/gocql/connectionpool.go:349 +0xca
github.com/gocql/gocql.(*policyConnPool).Close(0xc42006e180)
	/Users/rwilkes/code/go/src/github.com/gocql/gocql/connectionpool.go:198 +0x185
github.com/gocql/gocql.(*Session).Close(0xc420236000)
```

**Comment by kpodejma** [comment]
Problem occurs when SslOpts are set. Without SSL is ok.
ex.
```
cluster.SslOpts = &gocql.SslOptions{
		EnableHostVerification: false,
	}
```

**Comment by Zariel** [comment]
@richardwilkes thanks for the report, guess my comment in closeWithError was pertinent...
