### ISSUE TITLE
Segfault on query execution

### ISSUE THREAD

**Issue by gronka** [gocql/gocql#1089]
### What version of Cassandra are you using?
3.11.2

### What version of Gocql are you using?
whatever master is today

### What did you do?
```
func dropTables() {
	fmt.Println("dropping tables")
	drop_str := "DROP TABLE IF EXISTS "
	for _, table := range tables_map {
		cmd := drop_str + table + ";"
		fmt.Println(cmd)
		if err := s.Query(cmd).Exec(); err != nil {
			panic(err)
		}
	}
}
```

### What did you expect to see?
Expected table to be dropped

### What did you see instead?
(with gocql_debug enabled)
```
~/projects/src/bitbucket.org/gronka/bapi/dist (vertical-landing) $ ./bapi --reinit
2018/04/11 20:24:37 gocql: Session.handleNodeUp: 127.0.0.1:9042
dropping tables
DROP TABLE IF EXISTS bolt.events;
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12af2c6]

goroutine 1 [running]:
github.com/gocql/gocql.(*Session).Query(0x0, 0xc4200280c0, 0x21, 0x0, 0x0, 0x0, 0x1)
	/Users/taylor/projects/src/github.com/gocql/gocql/session.go:314 +0x26
main.dropTables()
	/Users/taylor/projects/src/bitbucket.org/gronka/bapi/go/tables.go:80 +0x1da
main.main()
	/Users/taylor/projects/src/bitbucket.org/gronka/bapi/go/main.go:43 +0x40d
```

### Other notes
Running  on MacOS
Used golang 1.10 and 1.9
Using ByteOrderedPartitioner on Cassandra (only change from default settings)

**Comment by gronka** [comment]
Same issue occurring on Ubuntu 16.04. Same Cassandra version and golang 1.9 and ByteOrderedPartitioner:

```
~/projects/src/bitbucket.org/gronka/bapi/go (vertical-landing) $ ./bapi --reinit
dropping tables
DROP TABLE IF EXISTS bolt.events
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6bfc46]

goroutine 1 [running]:
github.com/gocql/gocql.(*Session).Query(0x0, 0xc4200146c0, 0x20, 0x0, 0x0, 0x0, 0x20)
	/home/tgronka/projects/src/github.com/gocql/gocql/session.go:314 +0x26
main.dropTables()
	/home/tgronka/projects/src/bitbucket.org/gronka/bapi/go/tables.go:80 +0x1d4
main.main()
	/home/tgronka/projects/src/bitbucket.org/gronka/bapi/go/main.go:40 +0x460
```

**Comment by Zariel** [comment]
The session which has `Query` being called on it is nil, is it initialised correctly?

**Comment by gronka** [comment]
This works..
```
	casshost := "127.0.0.1"

	cluster := gocql.NewCluster(casshost)
	cluster.Keyspace = "bolt"
	cluster.ProtoVersion = 3
	cluster.Consistency = gocql.One
	s, err := cluster.CreateSession()
	if err != nil {
		log.Fatal(err)
	}

	defer s.Close()

	flag.Parse()
	if *reinit == true {

		fmt.Println("dropping tables")
		drop_str := "DROP TABLE IF EXISTS bolt.events"
		cmd := drop_str
		fmt.Println(cmd)
		if err := s.Query(cmd).Exec(); err != nil {
			panic(err)
		}

	}
```

This is a minimized version of what I currently have, which also works:
```
	casshost := "127.0.0.1"

	cluster := gocql.NewCluster(casshost)
	cluster.Keyspace = "bolt"
	cluster.ProtoVersion = 3
	cluster.Consistency = gocql.One
	s, err := cluster.CreateSession()
	if err != nil {
		log.Fatal(err)
	}

	defer s.Close()

	flag.Parse()
	if *reinit == true {
		dropTables()
        }
```

dropTables in tables.go:
```
	func dropTables() {
	fmt.Println("dropping tables")
	drop_str := "DROP TABLE IF EXISTS "
	for _, table := range tables_map {
		cmd := drop_str + table
		fmt.Println(cmd)
		if err := s.Query(cmd).Exec(); err != nil {
			panic(err)
		}
	}
}
```

No idea why this error would suddenly start occurring. Seems like my options are to recode this until I get to the breaking part, or try another driver. If it matters, this is reproducible with a variety of CQL statements (possibly all of them).

**Comment by gronka** [comment]
Ah, got it!

In this chunk
```
s, err := cluster.CreateSession()
	if err != nil {
		log.Fatal(err)
	}
```

I used `:=`, which I must created a new, local variable `s`. And my code "suddenly" started segfaulting because I randomly thought "I'll add an error check here to see what I catch."
