### ISSUE TITLE
panic when closing a session under high load

### ISSUE THREAD

**Issue by gengstrand** [gocql/gocql#1329]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
2.2

### What version of Gocql are you using?
latest

### What did you do?
Load testing in Kubernetes. The section titled [Spinning up the Services](https://github.com/gengstrand/clojure-news-feed/tree/master/server/k8s) for precise instructions on how to repro this. Do not run this command.
`kubectl create -f feed-deployment.yaml`
In its place, run this command instead.
`kubectl create -f feed9-deployment.yaml`

### What did you expect to see?

Somewhat even throughput and latency with no errors which is what I see when running the same load test on feature identical microservices implemented in other programming languages and with other Cassandra drivers.

### What did you see instead?
Throughput was about 10,000 create outbound RPM for the first 10 minutes. After that, throughput became highly sporadic and very low. Latency because very high. I see these messages in the application log about every 2 minutes.

`2019/07/06 21:39:24 http: panic serving 10.36.6.3:34900: runtime error: invalid memory address or nil pointer dereference
goroutine 12538508 [running]:
net/http.(*conn).serve.func1(0xc01e943540)
        /usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x822de0, 0xc0b7d0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/gocql/gocql.(*Session).Close(0x0)
        /go/src/github.com/gocql/gocql/session.go:366 +0x26
panic(0x822de0, 0xc0b7d0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/gocql/gocql.(*Query).defaultsFromSession(0xc0b5fe0120)
        /go/src/github.com/gocql/gocql/session.go:762 +0x32
github.com/gocql/gocql.(*Session).Query(0x0, 0x8c0a33, 0x7d, 0xc07351c780, 0x4, 0x4, 0xc0673a29f0)
        /go/src/github.com/gocql/gocql/session.go:336 +0xb2
`

---

If you are having connectivity related issues please share the following additional information
No connectivity issues.

### Describe your Cassandra cluster
please provide the following information

single node dev setup

**Comment by gengstrand** [comment]
Never mind. After reviewing both your code and mine, I realized that my code was ignoring the error on the call to cluster.CreateSession. You might want to consider adjusting the example code on your README file which is also ignoring the error on CreateSession.
