### ISSUE TITLE
MapScan panics on reading column of type `map<blob,int>`

### ISSUE THREAD

**Issue by dahankzter** [gocql/gocql#1330]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.0.7

### What version of Gocql are you using?
latest

### What did you do?
DDL:
```
CREATE KEYSPACE ks
  WITH REPLICATION = {
   'class' : 'SimpleStrategy',
   'replication_factor' : 1
  };

CREATE TABLE IF NOT EXISTS ks.tbl (
	id TIMEUUID PRIMARY KEY,
	data frozen<map<blob,int>>
);

INSERT INTO ks.tbl (id,data) VALUES (now(),{textAsBlob('some text'):1}) ;
```
Program:
```go
package main

import (
	"flag"
	"fmt"
	"strings"

	"github.com/gocql/gocql"
)

var (
	hosts string
)

func init() {
	flag.StringVar(&hosts, "hosts", "", "")
}

func main() {

	flag.Parse()

	cluster := gocql.NewCluster(strings.Split(hosts, ",")...)
	session, err := gocql.NewSession(*cluster)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer session.Close()

	it := session.Query("SELECT * FROM ks.tbl").Iter()
	defer func() {
		fmt.Println(it.Close())
	}()
	for {
		row := make(map[string]interface{})
		if !it.MapScan(row) {
			break
		}
		fmt.Println(row)
	}
}
```
### What did you expect to see?
I expected to see something along the line of a `map[string]int` in the second column.

### What did you see instead?

```
panic: reflect.MapOf: invalid key type []uint8

goroutine 158 [running]:
reflect.MapOf(0xb4eda0, 0x9805a0, 0xb4eda0, 0x987f40, 0x18, 0xc00007aa80)
	/usr/lib/go/src/reflect/type.go:1839 +0x74a
github.com/gocql/gocql.goType(0xb402e0, 0xc0008dce80, 0xb402e0, 0xc0008dce80)
	/home/henrik/go/pkg/mod/github.com/scylladb/gocql@v1.1.0/helpers.go:54 +0x9e3
github.com/gocql/gocql.CollectionType.New(0x4, 0x21, 0x0, 0x0, 0xb40320, 0xc000812860, 0xb40320, 0xc000812880, 0x0, 0x0)
	/home/henrik/go/pkg/mod/github.com/scylladb/gocql@v1.1.0/marshal.go:2212 +0x87
github.com/gocql/gocql.(*Iter).RowData(0xc00073c480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9e6c60, 0xc0000df640)
	/home/henrik/go/pkg/mod/github.com/scylladb/gocql@v1.1.0/helpers.go:306 +0x66b
github.com/gocql/gocql.(*Iter).MapScan(0xc00073c480, 0xc0002ab230, 0x9e6c60)
	/home/henrik/go/pkg/mod/github.com/scylladb/gocql@v1.1.0/helpers.go:403 +0x4a
```

**Comment by Zariel** [comment]
Go can not have slices as map keys so I would expect this to fail

**Comment by rjeczalik** [comment]
@Zariel `[]uint8` converts to `string` just fine: https://play.golang.org/p/KItnZyLp2ZV

**Comment by dahankzter** [comment]
Don't you think it would be nice to offer to read it as a `map[string]int` instead of just not supporting it @Zariel ?
