### ISSUE TITLE
panic in getReplicationFactorFromOpts when RF is 0

### ISSUE THREAD

**Issue by vrischmann** [gocql/gocql#1388]
### What version of Cassandra are you using?

3.11.5

### What version of Gocql are you using?

68f928edb90a8a33cc6a91eb5f8c4361edba73d4

### What did you do?

With a token aware host policy:

* Modified a keyspace with `NetworkTopologyStrategy` to have 0 replicas in one if its datacenter 
* Tried to create a session with the same keyspace set in the `ClusterConfig`

### What did you expect to see?

No panics

### What did you see instead?

A panic in gocql.

I have a keyspace in a cluster with two datacenters, DC1 and DC2. We wanted to remove the data for this keyspace from DC2, to do that I ran this query:

    alter KEYSPACE vincent_test WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '2', 'DC2': '0'};

This triggered a keyspace changed event and cause a panic in gocql:

```
panic: invalid replication_factor 0. Is the "vincent_test:dc=DC2" keyspace configured correctly?

goroutine 131 [running]:
github.com/gocql/gocql.getReplicationFactorFromOpts(0xc00030c180, 0x13, 0x6b3fe0, 0xc000140340, 0x4)
        /home/vincent/dev/go/src/github.com/gocql/gocql/topology.go:67 +0x2bd
github.com/gocql/gocql.getStrategy(0xc000188a00, 0xc, 0xc000188a00)
        /home/vincent/dev/go/src/github.com/gocql/gocql/topology.go:86 +0x1de
github.com/gocql/gocql.(*tokenAwareHostPolicy).updateReplicas(0xc0000f0460, 0xc00017c540, 0xc00014f620, 0xc)
        /home/vincent/dev/go/src/github.com/gocql/gocql/policies.go:455 +0x228
github.com/gocql/gocql.(*tokenAwareHostPolicy).KeyspaceChanged(0xc0000f0460, 0xc00014f620, 0xc, 0xc00014f5f5, 0x7)
        /home/vincent/dev/go/src/github.com/gocql/gocql/policies.go:443 +0xac
github.com/gocql/gocql.(*Session).handleKeyspaceChange(0xc0000a9500, 0xc00014f620, 0xc, 0xc00014f5f5, 0x7)
        /home/vincent/dev/go/src/github.com/gocql/gocql/events.go:127 +0x77
github.com/gocql/gocql.(*Session).handleSchemaEvent(0xc0000a9500, 0xc0001402c0, 0x1, 0x1)
        /home/vincent/dev/go/src/github.com/gocql/gocql/events.go:112 +0x2f3
created by github.com/gocql/gocql.(*eventDebouncer).flush
        /home/vincent/dev/go/src/github.com/gocql/gocql/events.go:64 +0x5f
```

The cause is [here](https://sourcegraph.com/github.com/gocql/gocql/-/blob/topology.go#L66-68).

Additionnally, the same panic can be triggered by forcing the keyspace in the [ClusterConfig](https://godoc.org/github.com/gocql/gocql#ClusterConfig):

```
panic: invalid replication_factor 0. Is the "vincent_test:dc=DC2" keyspace configured correctly?

goroutine 1 [running]:
github.com/gocql/gocql.getReplicationFactorFromOpts(0xc0001de120, 0x13, 0x6b3fe0, 0xc0000120e0, 0x4)
        /home/vincent/dev/go/src/github.com/gocql/gocql/topology.go:67 +0x2bd
github.com/gocql/gocql.getStrategy(0xc000156960, 0xc, 0xc000156960)
        /home/vincent/dev/go/src/github.com/gocql/gocql/topology.go:86 +0x1de
github.com/gocql/gocql.(*tokenAwareHostPolicy).updateReplicas(0xc0000f4460, 0xc000148390, 0x720088, 0xc)
        /home/vincent/dev/go/src/github.com/gocql/gocql/policies.go:455 +0x228
github.com/gocql/gocql.(*tokenAwareHostPolicy).KeyspaceChanged(0xc0000f4460, 0x720088, 0xc, 0x0, 0x0)
        /home/vincent/dev/go/src/github.com/gocql/gocql/policies.go:443 +0xac
github.com/gocql/gocql.(*Session).init(0xc00009d880, 0xc0000f44d0, 0x0)
        /home/vincent/dev/go/src/github.com/gocql/gocql/session.go:280 +0x5ca
github.com/gocql/gocql.NewSession(0xc0000aa920, 0x1, 0x1, 0x71e4b4, 0x5, 0x0, 0x23c34600, 0x23c34600, 0x2352, 0x720088, ...)
        /home/vincent/dev/go/src/github.com/gocql/gocql/session.go:166 +0x7fd
github.com/gocql/gocql.(*ClusterConfig).CreateSession(...)
        /home/vincent/dev/go/src/github.com/gocql/gocql/cluster.go:185
main.main()
        /home/vincent/tmp/gocql-rf0-repro/main.go:22 +0x340
```

But if I _don't_ force the keyspace and leave it blank, everything works fine.

I don't think this should panic because:
* this use case is legitimate
* gocql is fine with a RF of 0 in some cases
* the java driver doesn't have a problem with a RF of 0

Here is the code I used to reproduce the bug:

```go
package main

import (
	"log"
	"os"
	"time"

	"github.com/gocql/gocql"
	"github.com/sirupsen/logrus"
)

func main() {
	gocql.Logger = log.New(os.Stderr, "gocql", 0)

	cfg := gocql.NewCluster("127.0.10.1:9042")
	cfg.HostFilter = gocql.DataCentreHostFilter("DC1")
	cfg.Keyspace = "vincent_test"

	fallback := gocql.RoundRobinHostPolicy()
	cfg.PoolConfig.HostSelectionPolicy = gocql.TokenAwareHostPolicy(fallback)

	session, err := cfg.CreateSession()
	if err != nil {
		logrus.Fatal(err)
	}

	for range time.Tick(5 * time.Second) {
		iter := session.Query("SELECT * FROM vincent_test.foobar").Iter()
		var (
			id       gocql.UUID
			username string
		)
		for iter.Scan(&id, &username) {
			logrus.Printf("id: %s username: %s", id, username)
		}

		if err := iter.Close(); err != nil {
			logrus.Fatal(err)
		}
	}
}

```

and the schema:

```
CREATE KEYSPACE vincent_test WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '2', 'DC2': '0'}  AND durable_writes = true;
CREATE TABLE vincent_test.foobar ( id uuid PRIMARY KEY, username text );
```

I tested this with a cluster of 4 nodes, 2 in DC1 and 2 in DC2 on a local machine.

Happy to provide more information if necessary

**Comment by Skunnyk** [comment]
I have the same `panic` when using TokenAwarePolicy and a DC with replica: 0 (for example when following https://docs.scylladb.com/operating-scylla/procedures/cluster-management/add_dc_to_existing_dc/#add-new-dc to add a New DC).

However, it works if you don't include the DC in the keyspace, since https://github.com/gocql/gocql/commit/964d7011f63d85c0c135ca47e2d06032c6be391b fixed the behavior. This can be a workaround.
