### ISSUE TITLE
Why don't CREATE KEYSPACE and CREATE TABLE commands work?

### ISSUE THREAD

**Issue by SinaiNday** [gocql/gocql#1427]
I am trying to create the keyspace and tables within my Golang code using GoCQL library, is that possible? 

**It seems like  it is not implemented in the gocql session.go**
For example : 
   
 
```
package main

import (
	"fmt"
	"log"

	"github.com/gocql/gocql"
)

var Session *gocql.Session

func main() {
	// CONNECT AND CREATE A KEYSPACE

	var err error
	cluster := gocql.NewCluster("127.0.0.1")
	if err := Session.Query("CREATE  KEYSPACE  AAAA WITH REPLICATION ={ 'class' : 'SimpleStrategy', 'replication_factor' : 1 }").Exec(); err != nil {
		fmt.Println("Error while inserting AAAA")
		fmt.Println(err)
	}

	// SELECT THE CREATED KEYSPACE

	if err = Session.Query("USE AAAA").Exec(); err != nil {
		log.Fatal(err)
	}

	// CREATE TABLE

	if err := Session.Query("CREATE TABLE B ( Bid text PRIMARY KEY, Time timestamp,").Exec(); err != nil {
		fmt.Println("Error while creating B")
		fmt.Println(err)

	}

	// INITIALIZE THE SESSION USING THE KEYSPACE

	Session, err = cluster.CreateSession()
	if err != nil {
		panic(err)
	}
	fmt.Println("cassandra init done")
}

```
 

```
ERROR 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x148 pc=0x667d17]


goroutine 1 [running]:
github.com/gocql/gocql.(*Query).defaultsFromSession(0xc00010e120)
 /home/testbed/go/src/github.com/gocql/gocql/session.go:834 +0x37
github.com/gocql/gocql.(*Session).Query(0x0, 0x70c8c4, 0x61, 0x0, 0x0, 0x0, 0xc000000180)
 /home/testbed/go/src/github.com/gocql/gocql/session.go:375 +0xb2
main.main()


```

**Comment by Zariel** [comment]
session is nil, call `cluster.CreateSession()`

**Comment by SinaiNday** [comment]
thanks
