### ISSUE TITLE
[QUESTION] Using type PointType (from DSE)

### ISSUE THREAD

**Issue by JulienTant** [gocql/gocql#1520]
Hello,

I run Datastax Entreprise (v6.7.8 but it's quite irrelevant) and use in one of my table a column of type `org.apache.cassandra.db.marshal.PointType`. I can create a statement like `UPDATE table SET  point='POINT(12, 134)' WHERE ...` without issue, but when trying to turn the value of `point` into a parameter (using `?`) I can't pass a simple string there anymore.

I tried to understand how to implement a custom type for `org.apache.cassandra.db.marshal.PointType` but failed multiple time.

Could you give me a clue of how I can achieve this ? My issue now being that I'm generating tons of prepared statements (because I can't disable prepared statements for a given query) for nothing.

Thank you for your time and your help, it's higly appreciated.

**Comment by martin-sucha** [comment]
Hello,

> I run Datastax Entreprise (v6.7.8 but it's quite irrelevant) and use in one of my table a column of type org.apache.cassandra.db.marshal.PointType. I can create a statement like UPDATE table SET point='POINT(12, 134)' WHERE ... without issue, but when trying to turn the value of point into a parameter (using ?) I can't pass a simple string there anymore.
>
> I tried to understand how to implement a custom type for org.apache.cassandra.db.marshal.PointType but failed multiple time.

It would help if you included what you already tried in the original post. Especially any error message that you received. I'm not familiar with the PointType as I don't have access to DSE.

> Could you give me a clue of how I can achieve this ? My issue now being that I'm generating tons of prepared statements (because I can't disable prepared statements for a given query) for nothing.

You need to implement [gocql.Marshaler](https://pkg.go.dev/github.com/gocql/gocql#Marshaler) and [gocql.Unmarshaler](https://pkg.go.dev/github.com/gocql/gocql#Unmarshaler) for your point type. I have written some more docs, but it's not merged yet (I'm looking for someone to review it), see [an example](https://github.com/gocql/gocql/pull/1513/files#diff-661fb8d29e111cc75d4ad4d68fcebf90f94b1515db2c423c359362e1b7be231e).

You should probably check that the CQL type really is `org.apache.cassandra.db.marshal.PointType` when Marshaling/Unmarshaling, this could be done by checking that `Type()` is `gocql.TypeCustom` and `Custom()` is `org.apache.cassandra.db.marshal.PointType` in the [TypeInfo](https://github.com/gocql/gocql/blob/e49edf966d90/marshal.go#L2257) (but I'm guessing here).

Now the question is how the data type is serialized on the wire. Looking at the Datastax Python driver:

* https://github.com/datastax/python-driver/blob/653ef9721cc0618a590b212ea55cce2c84bdb94b/cassandra/marshal.py#L96-L97
* https://github.com/datastax/python-driver/blob/653ef9721cc0618a590b212ea55cce2c84bdb94b/cassandra/cqltypes.py#L1167-L1186

it appears to be encoded as [WKB](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry#Well-known_binary) (there is an example for 2D POINT in that wiki article).

**Comment by JulienTant** [comment]
Hi,
Sorry I was writing that on the go, here's the history of my code. As a note, i'm using the lib https://github.com/paulmach/orb which offers geometry representation + marshaling in WKB and WKT

Common between all those versions will the CQLPoint struct, which is a wrapper arround orb point and allows me to add my MarshalCQL method:

```go
type CQLPoint struct {
	orb.Point
}
```

Version 1:
```go
func (C CQLPoint) MarshalCQL(info gocql.TypeInfo) ([]byte, error) {
	return wkb.Marshal(C.Point, binary.BigEndian)
}
// error: OGCPoint is not normalized. OGCPoint should be defined/serialized as: POINT (2.334 44.88)
```
This doesn't generate any error in the cassandra logs, just this error at request


Version 2:
```go
func (C CQLPoint) MarshalCQL(info gocql.TypeInfo) ([]byte, error) {
	return []byte(fmt.Sprintf("POINT (%f %f)", C.Lon(), C.Lat())), nil
}
// error: com.esri.core.geometry.GeometryException: invalid shape type
```
And i'm getting this from cassandra logs:
```
 com.esri.core.geometry.GeometryException: invalid shape type
   at com.esri.core.geometry.OperatorImportFromWkbLocal.importFromWkb(OperatorImportFromWkbLocal.java:366)
   at com.esri.core.geometry.OperatorImportFromWkbLocal.executeOGC(OperatorImportFromWkbLocal.java:183)
   at com.esri.core.geometry.ogc.OGCGeometry.fromBinary(OGCGeometry.java:478)
   at org.apache.cassandra.db.marshal.geometry.OgcGeometry.fromOgcWellKnownBinary(OgcGeometry.java:137)
   at org.apache.cassandra.db.marshal.geometry.Point$1.fromWellKnownBinary(Point.java:46)
   at org.apache.cassandra.db.marshal.geometry.Point$1.fromWellKnownBinary(Point.java:18)
   at org.apache.cassandra.db.marshal.AbstractGeometricType$1.validate(AbstractGeometricType.java:42)
   at org.apache.cassandra.db.marshal.AbstractType.validate(AbstractType.java:221)
   at org.apache.cassandra.cql3.Constants$Marker.bindAndGet(Constants.java:405)
   at org.apache.cassandra.cql3.Constants$Setter.execute(Constants.java:434)
   at org.apache.cassandra.cql3.statements.UpdateStatement.addUpdateForKey(UpdateStatement.java:102)
   at org.apache.cassandra.cql3.statements.CQL3CasRequest$RowUpdate.applyUpdates(CQL3CasRequest.java:273)
   at org.apache.cassandra.cql3.statements.CQL3CasRequest.makeUpdates(CQL3CasRequest.java:240)
   at org.apache.cassandra.service.StorageProxy.cas(StorageProxy.java:248)
   at org.apache.cassandra.cql3.statements.ModificationStatement.lambda$executeWithCondition$4(ModificationStatement.java:513)
   at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:36)
   at io.reactivex.Single.subscribe(Single.java:2700)
   at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
   at io.reactivex.Single.subscribe(Single.java:2700)
   at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
   at org.apache.cassandra.concurrent.TPCRunnable.run(TPCRunnable.java:68)
   at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
   at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at org.apache.cassandra.concurrent.DebuggableThreadPoolExecutor$LocalSessionWrapper.run(DebuggableThreadPoolExecutor.java:332)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:79)
   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   at java.lang.Thread.run(Thread.java:748)
```

Sooo if I submit a WKB I have an explicit message telling me to submit a `POINT (x y)` (WKT), if I submit a WKT I see errors in cassandra log about parsing WKB... and finally, if I hardcode the POINT(X Y) as a string argument, it's working fine. I'm super confused ^^

And finally, a giant piece of code I used for my testing

```go
package main

import (
	"encoding/binary"
	"fmt"
	"log"
	"time"

	"github.com/gocql/gocql"
	"github.com/paulmach/orb"
	"github.com/paulmach/orb/encoding/wkb"
)

type CQLPoint struct {
	orb.Point
}

func (C CQLPoint) MarshalCQL(info gocql.TypeInfo) ([]byte, error) {
	fmt.Println(info.Custom())
	return []byte(fmt.Sprintf("POINT(%f %f)", C.Lon(), C.Lat())), nil
}

type CQLPointWKB struct {
	orb.Point
}

func (C CQLPointWKB) MarshalCQL(info gocql.TypeInfo) ([]byte, error) {
	fmt.Println(info.Custom())
	return wkb.Marshal(C.Point, binary.BigEndian)
}

func main() {
	cluster := gocql.NewCluster("localhost")
	cluster.Keyspace = "test_ks"
	cluster.DisableInitialHostLookup = true

	session, err := cluster.CreateSession()
	if err != nil {
		panic(err)
	}

	err = session.Query(`CREATE TABLE IF NOT EXISTS test_geopoint
	(
		ID BIGINT,
		pt 'PointType',
		PRIMARY KEY (ID)
	);`).Exec()
	if err != nil {
		panic(err)
	}

	// WKT
	q := session.Query("INSERT INTO test_geopoint (ID, pt) VALUES (?, ?)", time.Now().UnixNano(), CQLPoint{orb.Point{1, 2}})
	err = q.Exec()
	if err != nil {
		log.Println("WKT: " + err.Error())
	} else {
		log.Println("WKT: SUCCESS")
	}

	// WKB
	q = session.Query("INSERT INTO test_geopoint (ID, pt) VALUES (?, ?)", time.Now().UnixNano(), CQLPointWKB{orb.Point{1, 2}})
	err = q.Exec()
	if err != nil {
		log.Println("WKB: " + err.Error())
	} else {
		log.Println("WKB: SUCCESS")
	}

	// As a string
	q = session.Query("INSERT INTO test_geopoint (ID, pt) VALUES (?, ?)", time.Now().UnixNano(), "POINT(1 2)")
	err = q.Exec()
	if err != nil {
		log.Println("string WKT: " + err.Error())
	} else {
		log.Println("string WKT: SUCCESS")
	}

	// Hardcoded
	q = session.Query("INSERT INTO test_geopoint (ID, pt) VALUES (?, 'POINT(1 2)')", time.Now().UnixNano())
	err = q.Exec()
	if err != nil {
		log.Println("Hardcoded WKT: " + err.Error())
	} else {
		log.Println("Hardcoded WKT: SUCCESS")
	}

}
```

I hope those explaination can help you helping me

**Comment by JulienTant** [comment]
Well... I was re-reading and was like, how about trying LittleEndian? And... yup, that's it. >(
