### ISSUE TITLE
Token aware host policy causes panic

### ISSUE THREAD

**Issue by hamir-suspect** [gocql/gocql#1559]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
Cassandra 3.11.10 (not relevant)

### What version of Gocql are you using?
v0.0.0-20210313142353-65899a66288b (in go mod)

### What version of Go are you using?
go1.16.2 linux/amd64

### What did you do?
I have cluster pool config set up like this (qpp.config.cqllocaldc is name of my local datacenter (dc1), also at the moment the only data center).
```
Cluster.PoolConfig = gocql.PoolConfig{
		HostSelectionPolicy: gocql.TokenAwareHostPolicy(
			gocql.DCAwareRoundRobinPolicy(app.Config.CQLLocalDC),
			gocql.NonLocalReplicasFallback(),
			gocql.ShuffleReplicas(),
		)}
```
and I use gocqlx with it's query builder to create an insert, but that is irrelevant.

### What did you expect to see?
I expected it to go through with the insert, selects from the database work fine.

### What did you see instead?
once I try to query lib panicks and I get this:
index out of range [0] with length 0","details":[{"file":"panic.go","line":965,"function":"runtime.gopanic"},{"file":"panic.go","line":88,"function":"runtime.goPanicIndex"},{"file":"session.go","line":1829,"function":"github.com/gocql/gocql.createRoutingKey"},{"file":"session.go","line":1054,"function":"github.com/gocql/gocql.(*Query).GetRoutingKey"},{"file":"policies.go","line":548,"function":"github.com/gocql/gocql.(*tokenAwareHostPolicy).Pick"},{"file":"query_executor.go","line":58,"function":"github.com/gocql/gocql.(*queryExecutor).executeQuery"}]

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
My cluster is consisting of 3 nodes within dc1 and all are on rack1.

- output of `nodetool status`
Datacenter: dc1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns (effective)  Host ID                               Rack
UN  __ip___ 291.63 KiB  8            100.0%            b3c5b1fb-7fd9-460e-aec8-634f320ff878  rack1
UN  __ip___  236.25 KiB  8            100.0%            1a0a9a7e-2f72-44fc-b821-a4b1b02d1fdd  rack1
UN  __ip___  284.34 KiB  8            100.0%            6c4a26ec-bb58-45cd-bda1-650178ded98b  rack1

**Comment by martin-sucha** [comment]
Hmm, based on the above information it looks as if there are no bound values for the query when the panic is hit.

Could you share a snippet of your code that executes the query (e.g. the call to gocqlx). Or maybe a simple reproducer program?

**Comment by hamir-suspect** [comment]
I moved away from token aware host policy for now, I will come back to you.

**Comment by evildecay** [comment]
I also encountered a similar problem. The gocql version long ago did not have this problem. Now the latest version will cause this panic.
```go
luster.PoolConfig.HostSelectionPolicy = gocql.TokenAwareHostPolicy(gocql.RoundRobinHostPolicy())
```
```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb4e466]

goroutine 1 [running]:
github.com/gocql/gocql.compileMetadata(0x4, 0xc000550660, 0xc000780000, 0x17e, 0x249, 0xc000bd2000, 0x1934, 0x1d99, 0xc00015b200, 0xe, ...)
        D:/Develop/gocode/pkg/mod/github.com/gocql/gocql@v0.0.0-20211015133455-b225f9b53fa1/metadata.go:330 +0x2e6
github.com/gocql/gocql.(*schemaDescriber).refreshSchema(0xc00050a860, 0xe8c89b, 0x6, 0x6, 0x153e8e0)
        D:/Develop/gocode/pkg/mod/github.com/gocql/gocql@v0.0.0-20211015133455-b225f9b53fa1/metadata.go:293 +0x40d
github.com/gocql/gocql.(*schemaDescriber).getSchema(0xc00050a860, 0xe8c89b, 0x6, 0x0, 0x0, 0x0)
        D:/Develop/gocode/pkg/mod/github.com/gocql/gocql@v0.0.0-20211015133455-b225f9b53fa1/metadata.go:237 +0x109
github.com/gocql/gocql.(*Session).KeyspaceMetadata(0xc000218000, 0xe8c89b, 0x6, 0xc000291980, 0x0, 0x10)
        D:/Develop/gocode/pkg/mod/github.com/gocql/gocql@v0.0.0-20211015133455-b225f9b53fa1/session.go:526 +0x91
github.com/gocql/gocql.(*tokenAwareHostPolicy).updateReplicas(0xc00055a100, 0xc000291980, 0xe8c89b, 0x6)
        D:/Develop/gocode/pkg/mod/github.com/gocql/gocql@v0.0.0-20211015133455-b225f9b53fa1/policies.go:414 +0x9e
github.com/gocql/gocql.(*tokenAwareHostPolicy).KeyspaceChanged(0xc00055a100, 0xe8c89b, 0x6, 0x0, 0x0)
        D:/Develop/gocode/pkg/mod/github.com/gocql/gocql@v0.0.0-20211015133455-b225f9b53fa1/policies.go:404 +0x99
github.com/gocql/gocql.(*Session).init(0xc000218000, 0xc000426000, 0x0)
        D:/Develop/gocode/pkg/mod/github.com/gocql/gocql@v0.0.0-20211015133455-b225f9b53fa1/session.go:322 +0x775
github.com/gocql/gocql.NewSession(0xc0002903c0, 0x1, 0x1, 0xe8b00a, 0x5, 0x4, 0x2540be400, 0x23c34600, 0x2352, 0xe8c89b, ...)
        D:/Develop/gocode/pkg/mod/github.com/gocql/gocql@v0.0.0-20211015133455-b225f9b53fa1/session.go:173 +0x8a9
github.com/gocql/gocql.(*ClusterConfig).CreateSession(...)
        D:/Develop/gocode/pkg/mod/github.com/gocql/gocql@v0.0.0-20211015133455-b225f9b53fa1/cluster.go:205
git.wecise.com/wecise/common/cassandra.getClusterAndSession(0xe8c89b, 0x6, 0xc000209e00, 0xc000744000, 0x0, 0x0, 0xc000209d70)
        D:/Develop/projects/wecise/common/cassandra/cassandra.go:137 +0x678
git.wecise.com/wecise/common/cassandra.GetClientByOption(0xe8c89b, 0x6, 0xc000744000, 0x3, 0x0, 0x0)
        D:/Develop/projects/wecise/common/cassandra/cassandra.go:156 +0x45
git.wecise.com/wecise/common/multitenant.Init(0xf757c0, 0xc00000e018)
        D:/Develop/projects/wecise/common/multitenant/multitenant.go:308 +0x207
main.main()
        D:/Develop/projects/wecise/common/testrun.go:18 +0x9c

```

**Comment by OleksiienkoMykyta** [comment]
Can't reproduce such panic with the provided info.
Issue reported not responding since May 19, 2021, candidate to be closed as stale.
