### ISSUE TITLE
nil pointer in exec after timeouts

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#426]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5eac21]
goroutine 1393738 [running]:
github.com/gocql/gocql.(Conn).exec(0xc20813cb40, 0x7f4eeaf03110, 0xc2083803c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/gocql/gocql/conn.go:393 +0x391
github.com/gocql/gocql.(Conn).executeQuery(0xc20813cb40, 0xc2083fc9c0, 0x9c76e0)
/go/src/github.com/gocql/gocql/conn.go:529 +0x5f4
github.com/gocql/gocql.(Session).executeQuery(0xc208038820, 0xc2083fc9c0, 0x7f4650)
/go/src/github.com/gocql/gocql/session.go:222 +0x1da
github.com/gocql/gocql.(Query).Iter(0xc2083fc9c0, 0xc2083fc9c0)
/go/src/github.com/gocql/gocql/session.go:613 +0x107
github.com/gocql/gocql.(*Query).Exec(0xc2083fc9c0, 0x0, 0x0)
/go/src/github.com/gocql/gocql/session.go:603 +0x3a
```

**Comment by Zariel** [comment]
@xoraes what conditions trigger this? Is it after timeouts? I think there could be a data race when there is a timeout accessing the call.framer, but not sure. Could you run with the race detector?

**Comment by xoraes** [comment]
Sorry I had to make some major changes to our prod env (moved single dc to multi-dc cluster) to prevent timeouts and consequently I am no longer seeing the issue as of today. I no longer have timeouts and I do not see panic anymore. Looks like your have disabled timeout for now?

**Comment by Zariel** [comment]
@xoraes yeah I decided to remove timeouts until I could reproduce this error and clearly understand the races going on.

I think I have been able to create a test that reproduces this and have a fix in place to enable timeouts again.

The failure shown is as follows,
```
=== RUN TestQueryTimeoutReuseStream-4
==================
WARNING: DATA RACE
Read by goroutine 9:
  github.com/gocql/gocql.(*Conn).recv()
      /Users/chris/dev/go/src/github.com/gocql/gocql/conn.go:328 +0x295
  github.com/gocql/gocql.(*Conn).serve()
      /Users/chris/dev/go/src/github.com/gocql/gocql/conn.go:303 +0x47

Previous write by goroutine 5:
  github.com/gocql/gocql.(*Conn).exec()
      /Users/chris/dev/go/src/github.com/gocql/gocql/conn.go:407 +0x82c
  github.com/gocql/gocql.(*Conn).executeQuery()
      /Users/chris/dev/go/src/github.com/gocql/gocql/conn.go:529 +0x930
  github.com/gocql/gocql.(*Session).executeQuery()
      /Users/chris/dev/go/src/github.com/gocql/gocql/session.go:222 +0x2b1
  github.com/gocql/gocql.(*Query).Iter()
      /Users/chris/dev/go/src/github.com/gocql/gocql/session.go:613 +0x176
  github.com/gocql/gocql.(*Query).Exec()
      /Users/chris/dev/go/src/github.com/gocql/gocql/session.go:603 +0x47
  github.com/gocql/gocql.TestQueryTimeoutReuseStream()
      /Users/chris/dev/go/src/github.com/gocql/gocql/conn_test.go:530 +0x399
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:447 +0x133

Goroutine 9 (running) created at:
  github.com/gocql/gocql.Connect()
      /Users/chris/dev/go/src/github.com/gocql/gocql/conn.go:185 +0xa31
  github.com/gocql/gocql.(*SimplePool).connect()
      /Users/chris/dev/go/src/github.com/gocql/gocql/connectionpool.go:228 +0x2ce
  github.com/gocql/gocql.NewSimplePool()
      /Users/chris/dev/go/src/github.com/gocql/gocql/connectionpool.go:205 +0x7b4
  github.com/gocql/gocql.NewSession()
      /Users/chris/dev/go/src/github.com/gocql/gocql/session.go:63 +0x174
  github.com/gocql/gocql.(*ClusterConfig).CreateSession()
      /Users/chris/dev/go/src/github.com/gocql/gocql/cluster.go:104 +0x86
  github.com/gocql/gocql.TestQueryTimeoutReuseStream()
      /Users/chris/dev/go/src/github.com/gocql/gocql/conn_test.go:522 +0x1b5
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:447 +0x133

Goroutine 5 (running) created at:
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:555 +0xd4e
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:485 +0xe0
  main.main()
      github.com/gocql/gocql/_test/_testmain.go:292 +0x28c
==================
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x70 pc=0x84cea]
```
