### ISSUE TITLE
Panic on 32 bit arch

### ISSUE THREAD

**Issue by craveica** [gocql/gocql#541]
cat demo.go
```
package main

import (
        "github.com/gocql/gocql"
)

func main() {
        // connect to the cluster
        cluster := gocql.NewCluster("192.168.0.1", "192.168.0.2", "192.168.0.3")
        cluster.Keyspace = "example"
        cluster.Consistency = gocql.LocalQuorum
        session, _ := cluster.CreateSession()
        defer session.Close()
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x818b39c]

goroutine 1 [running]:
sync/atomic.CompareAndSwapUint64(0x1867e34c, 0x0, 0x0, 0x1, 0x0)
        /usr/lib/golang/src/sync/atomic/asm_386.s:76 +0xc
github.com/gocql/gocql.(*controlConn).reconnect(0x1867e340, 0x1867e300)
        /home/rav/Go/src/github.com/gocql/gocql/control.go:65 +0x53
github.com/gocql/gocql.NewSession(0x1860a390, 0x1, 0x1, 0x82b38f8, 0x5, 0x2, 0x23c34600, 0x0, 0x2352, 0x82b61e0, ...)
        /home/rav/Go/src/github.com/gocql/gocql/session.go:96 +0x448
github.com/gocql/gocql.(*ClusterConfig).CreateSession(0x1866c0a0, 0x1, 0x0, 0x0)
        /home/rav/Go/src/github.com/gocql/gocql/cluster.go:140 +0x45
main.main()
        /home/rav/Go/demo.go:12 +0x84

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_386.s:1662 +0x1

goroutine 18 [IO wait]:
net.runtime_pollWait(0xb690d2f0, 0x72, 0x186120a0)
        /usr/lib/golang/src/runtime/netpoll.go:157 +0x55
net.(*pollDesc).Wait(0x18652338, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:73 +0x35
net.(*pollDesc).WaitRead(0x18652338, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:78 +0x33
net.(*netFD).Read(0x18652300, 0x18684000, 0x1000, 0x1000, 0x0, 0xb6908018, 0x186120a0)
        /usr/lib/golang/src/net/fd_unix.go:232 +0x19a
net.(*conn).Read(0x18680000, 0x18684000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:172 +0xb9
bufio.(*Reader).fill(0x18682000)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x172
bufio.(*Reader).Read(0x18682000, 0x18686060, 0x8, 0x8, 0x80000000, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:207 +0x1b9
io.ReadAtLeast(0xb690c258, 0x18682000, 0x18686060, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/io/io.go:298 +0xab
io.ReadFull(0xb690c258, 0x18682000, 0x18686060, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/io/io.go:316 +0x51
github.com/gocql/gocql.readHeader(0xb690c258, 0x18682000, 0x18686060, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/rav/Go/src/github.com/gocql/gocql/frame.go:341 +0x69
github.com/gocql/gocql.(*Conn).recv(0x1868a000, 0x0, 0x0)
        /home/rav/Go/src/github.com/gocql/gocql/conn.go:391 +0x116
github.com/gocql/gocql.(*Conn).serve(0x1868a000)
        /home/rav/Go/src/github.com/gocql/gocql/conn.go:364 +0x2b
created by github.com/gocql/gocql.Connect
        /home/rav/Go/src/github.com/gocql/gocql/conn.go:199 +0x659

goroutine 19 [IO wait]:
net.runtime_pollWait(0xb690d278, 0x72, 0x186120a0)
        /usr/lib/golang/src/runtime/netpoll.go:157 +0x55
net.(*pollDesc).Wait(0x18688138, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:73 +0x35
net.(*pollDesc).WaitRead(0x18688138, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:78 +0x33
net.(*netFD).Read(0x18688100, 0x18685000, 0x1000, 0x1000, 0x0, 0xb6908018, 0x186120a0)
        /usr/lib/golang/src/net/fd_unix.go:232 +0x19a
net.(*conn).Read(0x18680020, 0x18685000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:172 +0xb9
bufio.(*Reader).fill(0x18682120)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x172
bufio.(*Reader).Read(0x18682120, 0x18686150, 0x8, 0x8, 0x80000000, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:207 +0x1b9
io.ReadAtLeast(0xb690c258, 0x18682120, 0x18686150, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/io/io.go:298 +0xab
io.ReadFull(0xb690c258, 0x18682120, 0x18686150, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/io/io.go:316 +0x51
github.com/gocql/gocql.readHeader(0xb690c258, 0x18682120, 0x18686150, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/rav/Go/src/github.com/gocql/gocql/frame.go:341 +0x69
github.com/gocql/gocql.(*Conn).recv(0x1868a120, 0x0, 0x0)
        /home/rav/Go/src/github.com/gocql/gocql/conn.go:391 +0x116
github.com/gocql/gocql.(*Conn).serve(0x1868a120)
        /home/rav/Go/src/github.com/gocql/gocql/conn.go:364 +0x2b
created by github.com/gocql/gocql.Connect
        /home/rav/Go/src/github.com/gocql/gocql/conn.go:199 +0x659

goroutine 20 [sleep]:
time.Sleep(0x6acfc00, 0x0)
        /usr/lib/golang/src/runtime/time.go:59 +0xe6
github.com/gocql/gocql.(*hostConnPool).fillingStopped(0x186720c0)
        /home/rav/Go/src/github.com/gocql/gocql/connectionpool.go:403 +0x48
created by github.com/gocql/gocql.(*hostConnPool).fill
        /home/rav/Go/src/github.com/gocql/gocql/connectionpool.go:369 +0x1f7

goroutine 21 [runnable]:
github.com/gocql/gocql.(*controlConn).heartBeat(0x1867e340)
        /home/rav/Go/src/github.com/gocql/gocql/control.go:34
created by github.com/gocql/gocql.createControlConn
        /home/rav/Go/src/github.com/gocql/gocql/control.go:29 +0x133
exit status 2
```

**Comment by Zariel** [comment]
Is this x86 or another arch?

**Comment by craveica** [comment]
x86

**Comment by Zariel** [comment]
According to https://golang.org/src/sync/atomic/doc.go?s=1207:1656#L36 CAS should work on 32 bit CPU's with MMX, which was introduced with Pentium.

**Comment by craveica** [comment]
Fixed. Thank you.
