### ISSUE TITLE
Panic: tokenAwareHostPolicy.Pick()

### ISSUE THREAD

**Issue by nemothekid** [gocql/gocql#544]
I believe this is related to #526, just in a new place, but I'm still debugging.

Stack trace:
```
goroutine 206373 [running]:
github.com/channelmeter/gocql.(*tokenAwareHostPolicy).Pick.func1(0x0, 0x0)
	/go/src/github.com/channelmeter/gocql/policies.go:232 +0x10e
github.com/channelmeter/gocql.(*policyConnPool).Pick(0xc82027a3f0, 0xc8210529c0, 0x0, 0x0, 0x0)
	/go/src/github.com/channelmeter/gocql/connectionpool.go:191 +0x10e
github.com/channelmeter/gocql.(*Session).executeQuery(0xc8203c01c0, 0xc8210529c0, 0xc821052900)
	/go/src/github.com/channelmeter/gocql/session.go:238 +0xfa
github.com/channelmeter/gocql.(*Query).Iter(0xc8210529c0, 0x1006680)
	/go/src/github.com/channelmeter/gocql/session.go:736 +0xc8
github.com/channelmeter/geard/tasks/youtube.RollupProfileLeaderDaily.func1(0xc82161f730, 0xc820182870, 0xc820de0240, 0xc8201403c0, 0xc820de0200, 0x16)
	/go/src/github.com/channelmeter/geard/tasks/youtube/profile_leader_rollup.go:48 +0x50a
created by github.com/channelmeter/geard/tasks/youtube.RollupProfileLeaderDaily
	/go/src/github.com/channelmeter/geard/tasks/youtube/profile_leader_rollup.go:85 +0x4e8
```
Relevant line:
```go
	return func() SelectedHost {
		if !hostReturned {
			hostReturned = true
			return selectedTokenAwareHost{host}
		}

		// fallback
		if fallbackIter == nil {
			fallbackIter = t.fallback.Pick(qry)
		}

		fallbackHost := fallbackIter()

		// filter the token aware selected hosts from the fallback hosts
232:	if fallbackHost.Info() == host {
			fallbackHost = fallbackIter()
		}

		return fallbackHost
	}
```

**Comment by Zariel** [comment]
Looks like fallbackHost needs a nil check
