### ISSUE TITLE
Unmarshaling frozen UDT with missing field panics

### ISSUE THREAD

**Issue by bkeroackdsc** [gocql/gocql#595]
```
016/01/15 22:03:14 http: panic serving x.x.x.x:47071: runtime error: slice bounds out of range
goroutine 66 [running]:
net/http.(*conn).serve.func1(0xc8204d2160, 0x7fe797c7e938, 0xc820074580)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/gocql/gocql.unmarshalUDT(0x7fe797c8a7e8, 0xc820400600, 0xc8203ca1a9, 0x13, 0x2098, 0x91a9c0, 0xc820459000, 0x0, 0x0)
	/go/src/github.com/gocql/gocql/marshal.go:1525 +0x1cd2
github.com/gocql/gocql.Unmarshal(0x7fe797c8a7e8, 0xc820400600, 0xc8203ca199, 0x23, 0x20a8, 0x91a9c0, 0xc820459000, 0x0, 0x0)
	/go/src/github.com/gocql/gocql/marshal.go:149 +0x955
github.com/gocql/gocql.unmarshalList(0x7fe797c7ef70, 0xc820366040, 0xc8203ca199, 0x20a8, 0x20a8, 0x913220, 0xc8203c58a0, 0x0, 0x0)
	/go/src/github.com/gocql/gocql/marshal.go:1006 +0xbb4
github.com/gocql/gocql.Unmarshal(0x7fe797c7ef70, 0xc820366040, 0xc8203ca191, 0x20b0, 0x20b0, 0x913220, 0xc8203c58a0, 0x0, 0x0)
	/go/src/github.com/gocql/gocql/marshal.go:137 +0x8a9
github.com/gocql/gocql.(*Iter).Scan(0xc8204ea820, 0xc8204fec80, 0x8, 0x8, 0x5a095f)
	/go/src/github.com/gocql/gocql/session.go:933 +0x8ee
github.com/gocql/gocql.(*Query).Scan(0xc8200e7e10, 0xc8204fec80, 0x8, 0x8, 0x0, 0x0)
	/go/src/github.com/gocql/gocql/session.go:816 +0xa7
main.getDeploymentRecord(0xc8203e0d80, 0xa746ad079d189162, 0x24ed5afb782773a6, 0xa746ad079d189162, 0x0, 0x0)
	/go/src/foo/db.go:152 +0x50e
main.confirmHandler(0x7fe797c85e40, 0xc820262840, 0xc8201381c0)
	/go/src/foo/handlers.go:177 +0xdc
net/http.HandlerFunc.ServeHTTP(0xd0cfe0, 0x7fe797c85e40, 0xc820262840, 0xc8201381c0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8203f2d70, 0x7fe797c85e40, 0xc820262840, 0xc8201381c0)
	/go/src/github.com/gorilla/mux/mux.go:103 +0x270
net/http.serverHandler.ServeHTTP(0xc8204529c0, 0x7fe797c85e40, 0xc820262840, 0xc8201381c0)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8204d2160)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

I have a UDT which previously had two fields: timestamp, text string.

I added a new field to the UDT: error flag (boolean).

I have a table that contains a frozen list of that UDT.

Trying to read a row that contains old versions of the frozen type panics.

This is the line that triggers the panic:
```go
// Event{} is the UDT
var events []Event
// /go/src/foo/db.go:52
err := s.Query(q, id).Scan(&id, &started, &ended, &success, &done, &newIDs, &oldIDs, &events)
```

Is this intended behavior?

**Comment by Zariel** [comment]
Can you provide a reproducible schema and example? Is it any different to this test? https://github.com/gocql/gocql/blob/3040d7651aec823f99944c19e5357973b93255ec/udt_test.go#L344

**Comment by Zariel** [comment]
I dont really see how that panics there, as it should have paniced at the line above, the code in question is

```go
		size := readInt(data[:4])
		data = data[4:]
```

What version of gocql are you using?
