### ISSUE TITLE
runtime: bad pointer in frame github.com/gocql/gocql.unmarshalUDT at 0xc82003e390: 0x4

### ISSUE THREAD

**Issue by ekle** [gocql/gocql#605]
i have this problem with the current master: 1a31c48ed2bf802c323bae85c69f7ab3110c8fb3
go version is 1.5.3 at linux-amd64 debian jessie
cassandra version is 2.1.12
i init the db with the following settings:
```
func InitDB(parms config.DB) error {
        // connect to the cluster
        cluster := gocql.NewCluster(parms.Hosts...)
        cluster.Keyspace = parms.Keyspace
        cluster.Consistency = gocql.Quorum
        cluster.ProtoVersion = 3
        cluster.RetryPolicy = &gocql.SimpleRetryPolicy{NumRetries: 3}
        cluster.Discovery = gocql.DiscoveryConfig{}

        if parms.Username != "" {
                auth := gocql.PasswordAuthenticator{}
                auth.Username = parms.Username
                auth.Password = parms.Password
                cluster.Authenticator = auth
        }

        session, err := cluster.CreateSession()
```
if i just add a log.Print() before ../db/log.go:40 the error disappears.
i have the problem on 2 servers.
it may is related to the use of zero-UUIDs in Maps-keys. but i'm not sure about this.
```
runtime: bad pointer in frame github.com/gocql/gocql.unmarshalUDT at 0xc82003e390: 0x4
fatal error: invalid stack pointer
runtime stack:
runtime.throw(0xadc450, 0x15)
/usr/local/go/src/runtime/panic.go:527 +0x96 fp=0x7f4337ffe950 sp=0x7f4337ffe938
runtime.adjustpointers(0xc82003e358, 0x7f4337ffeac8, 0x7f4337ffecb8, 0xc21880)
/usr/local/go/src/runtime/stack1.go:438 +0x2cf fp=0x7f4337ffea48 sp=0x7f4337ffe950
runtime.adjustframe(0x7f4337ffebd8, 0x7f4337ffecb8, 0x701)
/usr/local/go/src/runtime/stack1.go:505 +0x1b5 fp=0x7f4337ffeb00 sp=0x7f4337ffea48
runtime.gentraceback(0x41c3f0, 0xc82003e268, 0x0, 0xc820185380, 0x0, 0x0, 0x7fffffff, 0xb7f198, 0x7f4337ffecb8, 0x0, ...)
/usr/local/go/src/runtime/traceback.go:336 +0xa7e fp=0x7f4337ffec30 sp=0x7f4337ffeb00
runtime.copystack(0xc820185380, 0x4000)
/usr/local/go/src/runtime/stack1.go:616 +0x1a7 fp=0x7f4337ffed20 sp=0x7f4337ffec30
runtime.newstack()
/usr/local/go/src/runtime/stack1.go:801 +0xb9b fp=0x7f4337ffee98 sp=0x7f4337ffed20
runtime.morestack()
/usr/local/go/src/runtime/asm_amd64.s:330 +0x82 fp=0x7f4337ffeea0 sp=0x7f4337ffee98
goroutine 112 [copystack]:
runtime.getitab(0x96e740, 0x973600, 0xc82012f301, 0xc82012cd80)
/usr/local/go/src/runtime/iface.go:27 fp=0xc82003e270 sp=0xc82003e268
runtime.assertE2I2(0x96e740, 0x973600, 0xc8204304d0, 0xc820354378, 0xa1f800)
/usr/local/go/src/runtime/iface.go:368 +0x62 fp=0xc82003e2a8 sp=0xc82003e270
github.com/gocql/gocql.unmarshalUDT(0x7f433eb4e7d0, 0xc820428660, 0xc8203f2ab8, 0x14, 0x25b8, 0x973600, 0xc8204304d0, 0x0, 0x0)
***/jenkins/go/src/github.com/gocql/gocql/marshal.go:1431 +0xa4 fp=0xc82003ea58 sp=0xc82003e2a8
github.com/gocql/gocql.Unmarshal(0x7f433eb4e7d0, 0xc820428660, 0xc8203f2ab8, 0x14, 0x25b8, 0x973600, 0xc8204304d0, 0x0, 0x0)
***/jenkins/go/src/github.com/gocql/gocql/marshal.go:149 +0x955 fp=0xc82003eb40 sp=0xc82003ea58
github.com/gocql/gocql.unmarshalNullable(0x7f433eb4e7d0, 0xc820428660, 0xc8203f2ab8, 0x14, 0x25b8, 0x866da0, 0xc82001e698, 0x0, 0x0)
***/jenkins/go/src/github.com/gocql/gocql/marshal.go:181 +0x3ce fp=0xc82003ec58 sp=0xc82003eb40
github.com/gocql/gocql.Unmarshal(0x7f433eb4e7d0, 0xc820428660, 0xc8203f2ab8, 0x14, 0x25b8, 0x866da0, 0xc82001e698, 0x0, 0x0)
***/jenkins/go/src/github.com/gocql/gocql/marshal.go:114 +0x192 fp=0xc82003ed40 sp=0xc82003ec58
github.com/gocql/gocql.unmarshalMap(0x7f433eb4e3a0, 0xc82042e400, 0xc8203f2ab8, 0x98, 0x25b8, 0x8784a0, 0xc8204287b8, 0x0, 0x0)
***/jenkins/go/src/github.com/gocql/gocql/marshal.go:1098 +0xf04 fp=0xc82003f080 sp=0xc82003ed40
github.com/gocql/gocql.Unmarshal(0x7f433eb4e3a0, 0xc82042e400, 0xc8203f2a9c, 0xb4, 0x25d4, 0x8784a0, 0xc8204287b8, 0x0, 0x0)
***/jenkins/go/src/github.com/gocql/gocql/marshal.go:139 +0x8fc fp=0xc82003f168 sp=0xc82003f080
github.com/gocql/gocql.(*Iter).Scan(0xc82042c600, 0xc8203bee80, 0x8, 0x8, 0x8)
***/jenkins/go/src/github.com/gocql/gocql/session.go:933 +0x8ee fp=0xc82003f3a8 sp=0xc82003f168
***/***/***/db.(*iterHelper).Scan(0xc82042c600, 0xc8203bee80, 0x8, 0x8, 0xc82040d400)
***/jenkins/go/src/***/***/***/db/log.go:40 +0xd1 fp=0xc82003f530 sp=0xc82003f3a8
```

**Comment by Zariel** [comment]
Can you share a reproducible schema and query?

**Comment by ekle** [comment]
sorry no, even simple changes in the code, like adding a log.Print() removes the panic

**Comment by Zariel** [comment]
Can you try with go 1.6 beta2?

**Comment by ekle** [comment]
a go updated fixed the issue. thx.
