### ISSUE TITLE
panic in GetHostForToken

### ISSUE THREAD

**Issue by wyndhblb** [gocql/gocql#825]
Before the current release of the HostInfo things, if Cassandra "crashed" or there was a network partition and no nodes could be reached, gocql simply errored out saying "no nodes in pool" or something to that effect.  Now it panics

(this is on the master branch as of yesterday (2016-11-03))

```
panic: runtime error: index out of range

goroutine 378 [running]:
panic(0x4aecc20, 0xc420012110)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
/vendor/github.com/gocql/gocql.(*tokenRing).GetHostForToken(0xc43ad2b0c0, 0x5172560, 0xc43776f758, 0x8)
	/Users/boblanton/MyFitnessPal/anomoly//src//vendor/github.com/gocql/gocql/token.go:218 +0xa1
/vendor/github.com/gocql/gocql.(*tokenRing).GetHostForPartitionKey(0xc43ad2b0c0, 0xc43776f750, 0x8, 0x8, 0x0)
	/Users/boblanton/MyFitnessPal/anomoly//src//vendor/github.com/gocql/gocql/token.go:199 +0x7c
/vendor/github.com/gocql/gocql.(*tokenAwareHostPolicy).Pick(0xc4200c1560, 0x517a720, 0xc43509c200, 0xc43776f748)
	/Users/boblanton/MyFitnessPal/anomoly//src//vendor/github.com/gocql/gocql/policies.go:333 +0x14e
/vendor/github.com/gocql/gocql.(*queryExecutor).executeQuery(0xc42014a560, 0x517a720, 0xc43509c200, 0xc43776f74b, 0x3, 0xc432219d80)
	/Users/boblanton/MyFitnessPal/anomoly//src//vendor/github.com/gocql/gocql/query_executor.go:22 +0x91
/vendor/github.com/gocql/gocql.(*Session).executeQuery(0xc420120780, 0xc43509c200, 0xc432219d00)
	/Users/boblanton/MyFitnessPal/anomoly//src//vendor/github.com/gocql/gocql/session.go:376 +0x64
/vendor/github.com/gocql/gocql.(*Query).Iter(0xc43509c200, 0xc43509c200)
	/Users/boblanton/MyFitnessPal/anomoly//src//vendor/github.com/gocql/gocql/session.go:921 +0xe4
/vendor/github.com/gocql/gocql.(*Query).Exec(0xc43509c200, 0xc43fec8f50, 0x49)
	/Users/boblanton/MyFitnessPal/anomoly//src//vendor/github.com/gocql/gocql/session.go:904 +0x2b
....
```

Not sure if this is the desired behavior, it's certainly not for most DB use cases, where backpressure/circuit breaks is typically the answer for dead/out-of-band DBs.

**Comment by wyndhblb** [comment]
see https://github.com/gocql/gocql/pull/826 as a potential fix
