### ISSUE TITLE
Always having 'Connection reset by peer' when inserting data

### ISSUE THREAD

**Issue by Wenyi751** [gocql/gocql#832]
I have four docker containers (each for one node in the same cluster) on a ubuntu virtualbox. When I use the gocql driver on the host machine to insert data into cassandra, there will always raise this exception:

INFO  10:49:32 Unexpected exception during request; channel = [id: 0x00b9ea1e, /10.0.2.2:52301 => /172.18.0.6:9042]
java.io.IOException: Error while read(...): Connection reset by peer
	at io.netty.channel.epoll.Native.readAddress(Native Method) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:675) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

However, the cassandra works well and all data inserted successfully. When I use cqlsh to insert data directly, there will not raise the exception. 
How can I fix this exception? I have googled a lot but nothing can help me.

**Comment by Wenyi751** [comment]
I find out that it may be some issue with the vagrant, so close it.
