### ISSUE TITLE
panic: sync: inconsistent mutex state

### ISSUE THREAD

**Issue by colonelmo** [gocql/gocql#857]
```
panic: sync: inconsistent mutex state
goroutine 23 [running]:
panic(0x815f00, 0xc820d99830)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
sync.(*Mutex).Lock(0xc56818)
        /usr/lib/go-1.6/src/sync/mutex.go:75 +0x16d
sync.(*Pool).pinSlow(0xc2fae0, 0x0)
        /usr/lib/go-1.6/src/sync/pool.go:167 +0x38
sync.(*Pool).pin(0xc2fae0, 0x0)
        /usr/lib/go-1.6/src/sync/pool.go:160 +0x93
sync.(*Pool).Put(0xc2fae0, 0x9932a0, 0xc820976580)
        /usr/lib/go-1.6/src/sync/pool.go:72 +0x35
github.com/gocql/gocql.(*Conn).executeBatch(0xc8218d7180, 0xc82070db20, 0x161d6703)
        /home/colonelmo/gostuff/src/github.com/gocql/gocql/conn.go:1032 +0xab5
github.com/gocql/gocql.(*Batch).execute(0xc82070db20, 0xc8218d7180, 0xc38c60)
        /home/colonelmo/gostuff/src/github.com/gocql/gocql/session.go:568 +0x2b
github.com/gocql/gocql.(*queryExecutor).executeQuery(0xc820146be0, 0x7f2b105b92a0, 0xc82070db20, 0x20, 0x0, 0x0)
```

**Comment by Zariel** [comment]
What version of Go are you using?

**Comment by Zariel** [comment]
Given this is in the lock of the sync.Pool im going to close and suggest you open an issue with Go

**Comment by yuecong** [comment]
reopen this as we saw this error as well using both golang 1.12 and golang 1.14
```
fatal error: sync: inconsistent mutex state
goroutine 98188 [running]:
runtime.throw(0x19fce8f, 0x1e)
        /usr/local/go/src/runtime/panic.go:1112 +0x72 fp=0xc131df3980 sp=0xc131df3
950 pc=0x4345d2
sync.throw(0x19fce8f, 0x1e)
        /usr/local/go/src/runtime/panic.go:1098 +0x35 fp=0xc131df39a0 sp=0xc131df3
980 pc=0x434555
sync.(*Mutex).lockSlow(0x2ab5e58)
        /usr/local/go/src/sync/mutex.go:125 +0x1e9 fp=0xc131df39e8 sp=0xc131df39a0
 pc=0x480af9
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
sync.(*Pool).pinSlow(0x2a658c0, 0x0, 0x0)
        /usr/local/go/src/sync/pool.go:213 +0x272 fp=0xc131df3a68 sp=0xc131df39e8
pc=0x481582
sync.(*Pool).pin(0x2a658c0, 0xc117aaeab0, 0xc131df3ad8)
        /usr/local/go/src/sync/pool.go:206 +0x5e fp=0xc131df3a90 sp=0xc131df3a68 pc=0x4812de
sync.(*Pool).Get(0x2a658c0, 0x101ad8d, 0xc01149c1e0)
        /usr/local/go/src/sync/pool.go:128 +0x2f fp=0xc131df3ad8 sp=0xc131df3a90 pc=0x480f9f
github.com/m3db/m3/vendor/github.com/uber/tchannel-go.(*Channel).getRequestState(0xc000f301a0, 0x29ee550, 0x29ee550)
        /go/src/github.com/m3db/m3/vendor/github.com/uber/tchannel-go/retry.go:252 +0x31 fp=0xc131df3b20 sp=0xc131df3ad8 pc=0x101b781
github.com/m3db/m3/vendor/github.com/uber/tchannel-go.(*Channel).RunWithRetry(0xc000f301a0, 0x1c946c0, 0xc01149c1e0, 0xc131df3c28, 0x0, 0x0)
        /go/src/github.com/m3db/m3/vendor/github.com/uber/tchannel-go/retry.go:216 +0x90 fp=0xc131df3be0 sp=0xc131df3b20 pc=0x101b1d0
github.com/m3db/m3/vendor/github.com/uber/tchannel-go/thrift.(*client).Call(0xc000f2c570, 0x7f0bc68a2240, 0xc01149c1e0, 0x19d82c6, 0x4, 0x19da3d3, 0x6, 0x1c70d00, 0x2ab5e50, 0x1c70d40, ...)
        /go/src/github.com/m3db/m3/vendor/github.com/uber/tchannel-go/thrift/client.go:136 +0x18e fp=0xc131df3ca0 sp=0xc131df3be0 pc=0x102b15e
github.com/m3db/m3/src/dbnode/generated/thrift/rpc.(*tchanNodeClient).Health(0xc000f2a460, 0x7f0bc68a2240, 0xc01149c1e0, 0xc01149c0e0, 0x0, 0x1caeaa0)
        /go/src/github.com/m3db/m3/src/dbnode/generated/thrift/rpc/tchan-rpc.go:725 +0xbe fp=0xc131df3d28 sp=0xc131df3ca0 pc=0x10c609e
github.com/m3db/m3/src/dbnode/client.healthCheck(0x1cba5e0, 0xc000f2a460, 0x1cc7e60, 0xc009a28280, 0x0, 0x0)
        /go/src/github.com/m3db/m3/src/dbnode/client/connection_pool.go:312 +0x5d fp=0xc131df3d80 sp=0xc131df3d28 pc=0x10dd52d
github.com/m3db/m3/src/dbnode/client.(*connPool).healthCheckEvery.func1(0xc1125fa000, 0xc009a32180, 0xc000186ae0, 0x1cba5e0, 0xc000f2a460)
        /go/src/github.com/m3db/m3/src/dbnode/client/connection_pool.go:242 +0x1a2 fp=0xc131df3fb8 sp=0xc131df3d80 pc=0x1114cf2
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc131df3fc0 sp=0xc131df3fb8 pc=0x466bb1
created by github.com/m3db/m3/src/dbnode/client.(*connPool).healthCheckEvery
        /go/src/github.com/m3db/m3/src/dbnode/client/connection_pool.go:233 +0xfb
goroutine 1 [chan receive, 1 minutes]:
github.com/m3db/m3/src/x/os.WaitForInterrupt(0xc000186ae0, 0x0)
        /go/src/github.com/m3db/m3/src/x/os/interrupt.go:51 +0x9d
github.com/m3db/m3/src/query/server.Run(0xc0008026a0, 0x0, 0xc0000224d0, 0x3ff0000000000000, 0xc0001cf3f0, 0xc0001cf438, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/m3db/m3/src/query/server/query.go:431 +0x3902
main.main()
        /go/src/github.com/m3db/m3/src/cmd/services/m3coordinator/main/main.go:53 +0x1ef
```

**Comment by Zariel** [comment]
whats your `go env`?

**Comment by yuecong** [comment]
I can not see `go env` from my production as once it is built, we only installed the built binary there

we are using this dockerFile
https://github.com/m3db/m3/blob/master/docker/m3coordinator/Dockerfile

We tried to change the base image during build from 
```
FROM golang:1.12-alpine3.9 AS builder
```
to 
```
FROM golang:alpine3.11
``` to use golang 3.14

**Comment by yuecong** [comment]
ops. Maybe I should report this issue to Go team, not this ticket. mb

**Comment by Zariel** [comment]
Yeah I think this is a go issue not a gocql one

**Comment by LeslieRan** [comment]
> ops. Maybe I should report this issue to Go team, not this ticket. mb
Hello. Has the issue been solved?
