### ISSUE TITLE
The hostinfo pull request broke connecting to our 2.0.15 cluster

### ISSUE THREAD

**Issue by JelteF** [gocql/gocql#869]
Suddenly with the newest version we cannot connect to our cluster anymore. 
I'm getting this error:
```
panic: host missing connect ip address

goroutine 1 [running]:
github.com/gocql/gocql.Connect(0xc4200869a0, 0xc42001c480, 0x797e20, 0xc420064b80, 0xc42009c000, 0x0, 0x0, 0x0)
        /home/jelte/go/src/github.com/gocql/gocql/conn.go:160 +0xf5a
github.com/gocql/gocql.(*Session).connect(0xc42009c000, 0xc4200869a0, 0x797e20, 0xc420064b80, 0xc420064b80, 0xc42008f748, 0x2008f748)
        /home/jelte/go/src/github.com/gocql/gocql/session.go:629 +0x52
github.com/gocql/gocql.(*hostConnPool).connect(0xc420064b80, 0x0, 0x0)
        /home/jelte/go/src/github.com/gocql/gocql/connectionpool.go:482 +0x83
github.com/gocql/gocql.(*hostConnPool).fill(0xc420064b80)
        /home/jelte/go/src/github.com/gocql/gocql/connectionpool.go:392 +0x140
github.com/gocql/gocql.(*policyConnPool).addHost(0xc42001c420, 0xc4200869a0)
        /home/jelte/go/src/github.com/gocql/gocql/connectionpool.go:215 +0xe5
github.com/gocql/gocql.(*Session).handleNewNode(0xc42009c000, 0xc420010fc0, 0x10, 0x10, 0x2352, 0x2300)
        /home/jelte/go/src/github.com/gocql/gocql/events.go:199 +0x2e6
github.com/gocql/gocql.(*Session).handleNodeUp(0xc42009c000, 0xc420010fc0, 0x10, 0x10, 0x2352, 0x0)
        /home/jelte/go/src/github.com/gocql/gocql/events.go:254 +0x243
github.com/gocql/gocql.(*controlConn).setupConn(0xc420015e80, 0xc4200ae0e0, 0x1, 0x1)
        /home/jelte/go/src/github.com/gocql/gocql/control.go:261 +0x193
github.com/gocql/gocql.(*controlConn).connect(0xc420015e80, 0xc42000e050, 0x1, 0x1, 0x2, 0x0)
        /home/jelte/go/src/github.com/gocql/gocql/control.go:231 +0x18d
github.com/gocql/gocql.(*Session).init(0xc42009c000, 0xc42001c480, 0x0)
        /home/jelte/go/src/github.com/gocql/gocql/session.go:172 +0x359
github.com/gocql/gocql.NewSession(0xc420010b60, 0x1, 0x1, 0x6965bb, 0x5, 0x0, 0x23c34600, 0x23c34600, 0x2352, 0x696996, ...)
        /home/jelte/go/src/github.com/gocql/gocql/session.go:136 +0x86f
github.com/gocql/gocql.(*ClusterConfig).CreateSession(0xc420080120, 0x1, 0x1, 0xc420080120)
        /home/jelte/go/src/github.com/gocql/gocql/cluster.go:153 +0x62
main.main()
```
the code in question is this:
```go
        cluster := gocql.NewCluster("xxx.yyy.zzz.aaa")
        cluster.Keyspace = "feedly"
        session, err := cluster.CreateSession()
```

When printing the HostInfo from inside `ConnectAddress` I get the following list of HostInfo's:

```
[HostInfo connectAddress="redacted" peer="<nil>" rpc_address="<nil>" broadcast_address="<nil>" port=9042 data_centre="" rack="" host_id="" version="v0.0.0" state=UP num_tokens=0]
[HostInfo connectAddress="redacted" peer="<nil>" rpc_address="<nil>" broadcast_address="<nil>" port=9042 data_centre="" rack="" host_id="" version="v0.0.0" state=UP num_tokens=0]
[HostInfo connectAddress="redacted" peer="<nil>" rpc_address="<nil>" broadcast_address="<nil>" port=9042 data_centre="" rack="" host_id="" version="v0.0.0" state=UP num_tokens=0]
[HostInfo connectAddress="redacted" peer="<nil>" rpc_address="<nil>" broadcast_address="<nil>" port=9042 data_centre="" rack="" host_id="" version="v0.0.0" state=UP num_tokens=0]
[HostInfo connectAddress="redacted" peer="<nil>" rpc_address="<nil>" broadcast_address="<nil>" port=9042 data_centre="" rack="" host_id="" version="v0.0.0" state=UP num_tokens=0]
[HostInfo connectAddress="<nil>" peer="<nil>" rpc_address="<nil>" broadcast_address="<nil>" port=9042 data_centre="us-east" rack="1e" host_id="redacted" version="v2.0.15" state=UP num_tokens=256]
[HostInfo connectAddress="<nil>" peer="<nil>" rpc_address="<nil>" broadcast_address="<nil>" port=9042 data_centre="us-east" rack="1e" host_id="redacted" version="v2.0.15" state=UP num_tokens=256]
[HostInfo connectAddress="<nil>" peer="<nil>" rpc_address="<nil>" broadcast_address="<nil>" port=9042 data_centre="us-east" rack="1e" host_id="redacted" version="v2.0.15" state=UP num_tokens=256]
[HostInfo connectAddress="<nil>" peer="<nil>" rpc_address="<nil>" broadcast_address="<nil>" port=9042 data_centre="us-east" rack="1e" host_id="redacted" version="v2.0.15" state=UP num_tokens=256]
```

When going back to the previous commit in gocql everything is fine. So this #860 is the one that broke it.
Before I did get these messages, but the code continued and seemed fine:
```
2017/03/09 15:16:01 cannot unmarshal inet into *net.IP: invalid sized IP: got 0 bytes not 4 or 16
2017/03/09 15:16:02 cannot unmarshal inet into *net.IP: invalid sized IP: got 0 bytes not 4 or 16
```

**Comment by Highstead** [comment]
We're seeing a break as well in dev.  Havn't pushed to prod yet i suspect it had to do with rpc vs broadcast.

**Comment by Zariel** [comment]
Thanks for the report, reverted the change, will investigate

**Comment by thrawn01** [comment]
@Zariel @Highstead @JelteF I just had time to look at this and.... It's a little complicated.

@JelteF according to the`HostInfo` output you provided your cassandra cluster is missing `rpc_address` and `broadcast_address` for each of the nodes in the cluster. The `rpc_address` is the address cassandra clients should connect to, gocql currently uses `broadcast_address` as the client connect address. I think this behavior was introduced by accident, as I mention in the #860 PR notes: *Removed the need for `hostSource.localHasRpcAddr` which was misleading because it was actually the `broadcast_address`*

My patch attempted to preserve this functionality by preferring `broadcast_address` over `peer` and completely ignoring `rpc_address`.  I think the proper action is to connect to the `rpc_address` if available, else `peer` else `broadcast_address` (but I digress) 

The reason my patch failed to connect to this cluster was because it ignored the address provided via `gocql.NewCluster("xxx.yyy.zzz.aaa")` and attempted to fill the pool using the only the `broadcast_address` provided by cassandra which in this case was `nil`. Cassandra clusters that are configured with the correct `broadcast_address` don't have this issue which is why the tests passed and I didn't notice this issue during testing.

I have identified the issue in the code and will submit a patch shortly.
