### ISSUE TITLE
CQL time type is not supported? (similar to #828 )

### ISSUE THREAD

**Issue by laher** [gocql/gocql#904]
_Please excuse my lack of understanding on this - I'm new to cassandra and working with a codebase I'm also new to._

We have fields of type date and time in a CQL table. In some test code we try to marshal  a `select *` statement onto a `map[string]interface{}`. It panics unless I exclude the time field. 

 * Notably, until I re-vendored to a recent version, it would panic on the date fields aswell (date support was added for #828 ). So, it seems like the time type ought to get similar attention to the date type.

So, I'm concluding that some similar handling could be added for the 'time' type...

1. Here's an example stack trace:

```
goroutine 145 [running]:
testing.tRunner.func1(0xc420260a90)
        .../go1.8/src/testing/testing.go:622 +0x29d
panic(0x84cf00, 0xc4202dcab0)
        .../go1.8/src/runtime/panic.go:489 +0x2cf
reflect.New(0x0, 0x0, 0x0, 0x0, 0xc4202d99e0)
       .../go1.8/src/reflect/value.go:2130 +0x114
.../vendor/github.com/gocql/gocql.NativeType.New(0x4, 0x12, 0x0, 0x0, 0x8ec300, 0xc4202d99e0)
        .../vendor/github.com/gocql/gocql/marshal.go:1872 +0x92
.../vendor/github.com/gocql/gocql.(*NativeType).New(0xc4202f4460, 0x8ec300, 0xc4202d99e0)
        <autogenerated>:227 +0x67
.../vendor/github.com/gocql/gocql.(*Iter).RowData(0xc4201e18c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
       .../vendor/github.com/gocql/gocql/helpers.go:220 +0x561
github.com/movio/red/campaign-scheduler/vendor/github.com/gocql/gocql.(*Iter).MapScan(0xc4201e18c0, 0xc4202cc540, 0xc4201b7c00)
       .../vendor/github.com/gocql/gocql/helpers.go:297 +0x4c
.../vendor/github.com/gocql/gocql.(*Query).MapScan(0xc4201b7c00, 0xc4202cc540, 0x39, 0xc4201affc0)
        .../vendor/github.com/gocql/gocql/session.go:944 +0x71
 ..../my-code.(*cassandra).fetchRow(0xc420180078, 0x8f3182, 0x4, 0x8f321e, 0x4, 0x9029e3, 0x24, 0xc4201add20, 0x1, 0x1)
/cassandra_test.go:375 +0x243

```

2. Here's the simplified code snippet:

```
func (c *cassandra) fetchRow(id string) (map[string]interface{}, error) {
	q := fmt.Sprintf(`SELECT * FROM TABLE WHERE id = ? LIMIT 1;`, table)
	row := make(map[string]interface{})
	err := c.session.Query(q, tenant, uuid).MapScan(row)
	return row, err
}
```

**Comment by penberg** [comment]
@laher Correct, `gocql` indeed does not currently support the `time` CQL type.

**Comment by Zariel** [comment]
thanks for the report
